name: ece594n
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - pip:
    - git+https://github.com/geomstats/geomstats.git
    - jupyter
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - jupyterlab-code-formatter
    - RISE
