name: ece594n
channels:
  - conda-forge
dependencies:
  - numpy
  - pip
  - pip:
    - git+https://github.com/geomstats/geomstats.git
    - jupyter
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
    - jupyterlab-code-formatter
    - RISE
# Enable splitcell extension via the jupyter_nbextensions_configurator server extension
# https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/README.md